[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Monea.xyz"]

[workspace.dependencies]
monea_utils = { path = "crates/utils" }
monea_auth = { path = "crates/auth" }
monea_api = { path = "crates/api" }