project_name: Monea Appchain

layer1:
  chains:
  - name: ethereum-l1
    chain_id: 342836
    layer_number: 1
    block_time: 12

layer2:
  pipeline: {
    pre: [],
    post: [],
  }
  chains:
  - name: Monea L2 Devnet
    deploy: true
    chain_id: 2151908
    framework_type: OpStack
    layer_number: 2
    block_time: 2
    settlement:
      network_id: 2151908
    data_availability:
      type: Blobs
